export const plants = [
  {
    id: '1',
    name: 'Wild Strawberry',
    category: 'Berries',
    image: 'https://images.unsplash.com/photo-1586348943529-beaae6c28db9?w=400',
    unlocked: true,
  },
  {
    id: '2',
    name: 'Sea Beet',
    category: 'Leaves',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400',
    unlocked: true,
  },
  {
    id: '3',
    name: 'Wild Garlic',
    category: 'Leaves',
    image: 'https://unsplash.com/photos/green-leaves-on-brown-tree-branches-VI_PCpBIWpo',
    unlocked: true,
  },
  {
    id: '4',
    name: 'Elderflower',
    category: 'Flowers',
    image: 'image',
    unlocked: false,
  },
  {
    id: '5',
    name: 'Cloudberry',
    category: 'Berries',
    image: 'https://images.unsplash.com/photo-1596591868231-05e808fd131d?w=400',
    unlocked: true,
  },
  {
    id: '6',
    name: 'Spring Fieldcap',
    category: 'Fungi',
    image: 'https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?w=400',
    unlocked: false,
  },
  {
    id: '7',
    name: 'Jelly Ear',
    category: 'Fungi',
    image: 'image',
    unlocked: false,
  },
  {
    id: '8',
    name: 'Borage',
    category: 'Flowers',
    image: 'image',
    unlocked: true,
  },
  {
    id: '9',
    name: 'Nettle',
    category: 'Leaves',
    image: 'image',
    unlocked: true,
  },
  {
    id: '10',
    name: 'Nasturtium',
    category: 'Flowers',
    image: 'image',
    unlocked: false,
  }
];